name: build image
on:
  push:
    paths:
      - "version"
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Get version
        id: getVersion
        run: |
          echo ::set-output name=tag:: `cat version`
      - name: Download lbrynet
        run: |
          wget lbrynet.zip https://github.com/lbryio/lbry-sdk/releases/download/${{ steps.getVersion.outputs.tag }}/lbrynet-linux.zip
      - name: Unzip
        uses: montudor/action-zip@v0.1.1
        with:
          args: unzip lbrynet-linux.zip
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Github Package
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Build and Push container image
        uses: docker/build-push-action@v2
        with:
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.getVersion.outputs.tag }}
          labels: |
            org.opencontainers.image.source=${{ github.event.repository.clone_url }}
            org.opencontainers.image.revision=${{ steps.getVersion.outputs.tag }}
