name: Build image
on:
  push:
    paths:
      - "version"
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GHCR_TOKEN }}
      - name: Get version
        id: getVersion
        run: |
          echo ::set-output name=version::`cat version`
      - name: Download lbrynet
        run: |
          wget -nv https://github.com/lbryio/lbry-sdk/releases/download/${{ steps.getVersion.outputs.version }}/lbrynet-linux.zip
      - name: Unzip
        uses: montudor/action-zip@v0.1.1
        with:
          args: unzip lbrynet-linux.zip
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Github Package
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Build and Push container image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ghcr.io/laysi/docker-lbrynet:${{ steps.getVersion.outputs.version }}
          labels: |
            org.opencontainers.image.source=${{ github.event.repository.clone_url }}
            org.opencontainers.image.revision=${{ steps.getVersion.outputs.version }}
      - name: Build and Push container image(latest)
        uses: docker/build-push-action@v2
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ghcr.io/laysi/docker-lbrynet:${{ steps.getVersion.outputs.version }}
          labels: |
            org.opencontainers.image.source=${{ github.event.repository.clone_url }}
            org.opencontainers.image.revision=${{ steps.getVersion.outputs.version }}