name: Get latest release version
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  get-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GHCR_TOKEN }}
      - name: Fetch release version
        run: |
          curl -sL https://api.github.com/repos/lbryio/lbry-sdk/releases/latest | \
          jq -r ".tag_name" > version
      - name: Check for modified files
        id: git-check
        run: echo ::set-output name=modified::$([ -z "`git status --porcelain`" ] && echo "false" || echo "true")
      - name: Commit latest release version
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -am | cat version
          git push
